# Generated by Django 2.1.5 on 2019-01-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=20)),
                ('belong', models.CharField(max_length=20)),
                ('channel_id', models.CharField(max_length=20)),
                ('youtube_url', models.CharField(max_length=80)),
                ('tag1', models.CharField(max_length=20)),
            ],
        ),
    ]
